# Generated by Django 6.1 on 2026-08-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Pemula', 'Pemula'), ('Menengah', 'Menengah'), ('Lanjutan', 'Lanjutan')], default='Pemula', max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Durasi dalam jam')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
